services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: always
    environment:
      - http_proxy=socks5://172.17.0.1:{PORT}
      - https_proxy=socks5://172.17.0.1:{PORT}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --rolling-restart --schedule "1 0 * * * *"
  globalping:
    image: globalping/globalping-probe:latest
    container_name: globalping
    restart: always
    environment:
      - GP_ADOPTION_TOKEN={GP_ADOPTION_TOKEN}
    network_mode: host
    logging:
      driver: local
  vlmcsd:
    image: mikolatero/vlmcsd:latest
    container_name: vlmcsd
    restart: always
    ports:
      - {PORT}:1688
  rustdesk_hbbs:
    image: rustdesk/rustdesk-server:latest
    command: hbbs
    volumes:
      - ./rustdesk:/root
    container_name: rustdesk_hbbs
    restart: always
    ports:
      - {PORT}:21115
      - {PORT}:21116
      - "{PORT}:21116/udp"
    depends_on:
      - rustdesk_hbbr
  rustdesk_hbbr:
    image: rustdesk/rustdesk-server:latest
    command: hbbr
    volumes:
      - ./rustdesk:/root
    container_name: rustdesk_hbbr
    restart: always
    ports:
      - {PORT}:21117
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    ports:
      - {PORT}:80
    volumes:
      - ./vaultwarden:/data
      - ./vaultwarden/env:/.env
  nginx_exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: nginx_exporter
    restart: always
    ports:
      - {PORT}:9113
    command: --nginx.scrape-uri=http://172.17.0.1:{PORT}/stub_status
